import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { getSession } from "@/lib/session";
import { isAdminByFid } from "@/lib/admin";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const isAdmin = isAdminByFid(session?.fid ?? null);
  // Fetch CSRF on initial layout render to prime cookie in SSR
  // This is safe and lightweight; header values are exposed for clients if needed
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full border-b">
          <nav className="max-w-5xl mx-auto px-4 py-3 flex items-center gap-4 text-sm">
            <Link href="/" className="font-medium">Home</Link>
            <Link href="/feed" className="hover:underline">Feed</Link>
            <Link href="/projects" className="hover:underline">Projects</Link>
            <Link href="/projects/new" className="hover:underline">New Project</Link>
            <Link href="/collaborators/me" className="hover:underline">My Profile</Link>
            {session && <Link href="/inbox" className="hover:underline ml-auto">Inbox</Link>}
            {isAdmin && <Link href="/admin/reports" className="hover:underline">Admin</Link>}
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
